version: "2"

services:
  db:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=soiled_api
      - POSTGRES_PASSWORD=postgres
    ports:
      - "18000:5432"
